language: php

php:
  - 5.1
  - 5.2
  - 5.3
  - 5.4

before_script:
  - phpize && ./configure && make && sudo make install
  - echo "extension=runkit.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
notifications:
  email:
    - reeze.xia@gmail.com