language: php

php:
  - 5.4

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

before_script:
  - phpize && ./configure --enable-runkit-sandbox --enable-runkit-super --enable-runkit-sandbox && make && sudo make install
  - echo "extension=runkit.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script: sh travis/run-test.sh

notifications:
  email:
    - reeze.xia@gmail.com